dictionaries = [
    "en_us",
    "en_gb",
]
words = [
    "appender",
    "bignum",
    "cobertura",
    "duckdb",
    "hugeint",
    "kcov",
    "libduckdb",
    "oxlint",
    "smallint",
    "sqlnull",
    "tinyint",
    "ubigint",
    "uhugeint",
    "uinteger",
    "usmallint",
    "utinyint",
    "varchar",
]
flag_words = [
    "todo",
    "fixme",
]
