# https://docs.helix-editor.com/configuration.html

theme = "catppuccin_mocha"

[editor]
mouse = false
bufferline = "multiple"
cursorline = true
rulers = [80, 100]

# recommended at end of: https://docs.helix-editor.com/editor.html
end-of-line-diagnostics = "hint"
[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

# TIP: Bulk edit: % (select all) -> s (select by regex)

[keys.normal]
C-s = ":w"
"C-/" = "toggle_comments"

[keys.normal.space]
W = ":toggle soft-wrap.enable"
H = ":toggle lsp.display-inlay-hints"
