"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Max Milton"
email = "max@2okki.com"

[signing]
behavior = "own"
backend = "gpg"
key = "C174762F23AF46AF" # max@2okki.com [S]

[aliases]
l = ["log", "-r", "::@", "-T", "builtin_log_comfortable"]
ll = ["log", "-r", "::@", "-T", 'builtin_log_comfortable ++ diff.stat(72) ++ "\n"']
# TODO: Remove once sync PR lands: https://github.com/jj-vcs/jj/pull/6826
sync = ["util", "exec", "--", "sh", "-c", "jj git fetch && jj rebase -d 'trunk()' --skip-emptied"]
clone = ["git", "clone", "--colocate"]

# https://github.com/sunshowers/dotfiles/blob/main/dot_jjconfig.toml
s = ["show", "@-"]

# https://oppi.li/posts/configuring_jujutsu/
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[git]
write-change-id-header = true

[ui]
default-command = "log" # "log" = "jj", "status" = "j" shell alias
merge-editor = "mergiraf"
