name: audit

on:
  push:
    branches:
      - master
    paths:
      - ".bun/**"
  pull_request:
  merge_group:
  workflow_dispatch:
  schedule:
    - cron: "28 6 * * 4"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash
    working-directory: ./.bun/install/global

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version: latest
      # audit needs a lockfile so generate one first
      - run: bun install --lockfile-only
      - run: bun audit
